# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Scratch (API) Documentation
site_url: https://scratch-api.github.io/docs/
site_description: Documentation for the Scratch API and other things

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - social
  - search


extra:
  social:
    # Took this from the goboscript mkdocs yml file
    - icon: fontawesome/brands/github
      link: https://github.com/scratch-api
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mgxyyfnfk8